### PR TITLE
#43 - Add support for project's relative path

### PR DESCRIPTION
**Pull request by medalex**

### CODE REVIEW

**Comment by flcdrg** [comment]
I think AppVeyor is having trouble with the analyzers. I might need to update them

**Comment by medalex** [comment]
I updated analyzer but seems check is still failing

**Comment by medalex** [comment]
I have updated all analyzers but still AppVeyor takes old ones. Can you please advise something?

**Comment by flcdrg** [comment]
I'll try and have a look in the next day or two.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by medalex** [comment]
Hi, are there any news about the analyzers issue?

**Pull request closed without merging**
